name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.2, 8.3, 8.4]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, pdo_mysql, bcmath
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Cache Composer cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer-cache-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Copy .env.ci
        run: cp .env.ci .env

      - name: Configure .env for CI
        run: |
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_PORT=.*/DB_PORT=3306/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=laravel_test/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=root/' .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Cache Laravel config
        run: php artisan config:cache

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h127.0.0.1 -uroot -proot --silent; then
              break
            fi
            sleep 2
          done

      - name: Run migrations with debug
        run: php artisan migrate --force -vvv
        timeout-minutes: 3

      - name: Seed database with debug
        run: php artisan db:seed --force -vvv
        timeout-minutes: 3

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress --memory-limit=1G

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=PSR12 app/

      - name: Run tests
        run: php artisan test -v --parallel

      - name: Upload test logs if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: storage/logs

      - name: Display PHP version
        run: php -v

      - name: Display Composer version
        run: composer -V
